### ISSUE TITLE
Git Account Creation

### ISSUE THREAD

**Issue by kbabu007** [SIGC-DevOps-205/Repo-DevOps-205#1]
In progress

**Comment by Aarthi169** [comment]
In progress

**Comment by brindha2025** [comment]
Status updated to in progress

**Comment by 7Keerthana** [comment]
Status updated to in progress

**Comment by arthi0245** [comment]
Status updated to in  progress

**Comment by Maha2405** [comment]
In progress

**Comment by Kayal0706** [comment]
Status updated into progress

**Comment by Santh2004** [comment]
Status updated to in progress

**Comment by Ang2405** [comment]
Status updated in to progress

**Comment by kanishka84688** [comment]
Status updated to in progress

**Comment by Kaveri286** [comment]
Status updated to in progress

**Comment by Maha2405** [comment]
Git account has be created maha2405

**Comment by kanishka84688** [comment]
Account can be created kanishka84688

**Comment by kbabu007** [comment]
Some students are not updated

**Comment by Ang2405** [comment]
Account can be created Ang2405

**Comment by 7Keerthana** [comment]
Created repo, status updated to in progress

**Comment by revathikumarkalai** [comment]
In progress

**Comment by Kayal0706** [comment]
Account can be created kayal0706

**Comment by karthikalucky** [comment]
Working on progress

**Comment by dharanisathya** [comment]
Working on progress

**Comment by keerthanagop** [comment]
Status updated into progress

**Comment by Aarthi169** [comment]
Review

**Comment by 7Keerthana** [comment]
Status updated to review

**Comment by Durga3025** [comment]
Status updated to in review

**Comment by Santh2004** [comment]
Status updated to in review

**Comment by Maha2405** [comment]
Status updated to review

**Comment by Kaviyas1013** [comment]
Status updated into progress

**Comment by Raji026** [comment]
Status updated into progress

**Comment by revathikumarkalai** [comment]
Status updated into progress

**Comment by Guna288** [comment]
Status change into review

**Comment by Guna288** [comment]
Status change into review

**Comment by nivedha62004** [comment]
Status change into review

**Comment by rajeshwari031** [comment]
Status updated into progress

**Comment by kanishka84688** [comment]
Change into status into review

**Comment by kbabu007** [comment]
GitHub account created done by students. Hence, closing this task.
