### ISSUE TITLE
Move Code to Stage

### ISSUE THREAD

**Issue by kbabu007** [SIGC-DevOps-205/Repo-DevOps-205#10]

**Comment by salika123** [comment]
Status updated to in progress

**Comment by Swathi028** [comment]
Status updated in progress

**Comment by Lachumi** [comment]
Status updated to in progress

**Comment by suhashini37** [comment]
States updated in progress

**Comment by nivetham2005** [comment]
States updated in to progress

**Comment by salika123** [comment]
Report created Repo-sahayasalika

**Comment by salika123** [comment]
Branch created branch-sahayasalika

**Comment by salika123** [comment]
Repo created Repo-salika123

**Comment by karthikalucky** [comment]
Status updated in program

**Comment by brindha2025** [comment]
Status updated to in progress

**Comment by Santh2004** [comment]
Status updated to in progress

**Comment by mathanki2005** [comment]
Status updated in progress

**Comment by DharaniShree10** [comment]
Status updated in progress

**Comment by Aarthi169** [comment]
Status updated in progress

**Comment by bhuvanasri3101** [comment]
Status  updated in progress

**Comment by Maha2405** [comment]
Status updates to in progress

**Comment by dharanisathya** [comment]
Status updated to in progress

**Comment by gopika030** [comment]
Status updated in progress

**Comment by nivedha62004** [comment]
Status change into review

**Comment by 7Keerthana** [comment]
Status updated to in progress

**Comment by Guna288** [comment]
Status updated to in progress

**Comment by kiruthika021** [comment]
status updated to in progress

**Comment by Ang2405** [comment]
Status updated to in progress

**Comment by rajeshwari031** [comment]
Status updated in to progress

**Comment by Manisha8667** [comment]
Status is updated in progress

**Comment by Afrin2000** [comment]
Status updated to in progress

**Comment by arthi0245** [comment]
Status updated to in progress

**Comment by Kaviyas1013** [comment]
Status updated to in progress

**Comment by keerthanagop** [comment]
Status updated to in progress

**Comment by Raji026** [comment]
Status updated to in progress

**Comment by Raji026** [comment]
Status updated to in progress

**Comment by Ranjanaj445** [comment]
Status updated to inprogress

**Comment by Kayal0706** [comment]
Status updated in progress

**Comment by Rkrive** [comment]
Status updated in progress

**Comment by Pavithirajeganathan** [comment]
Status updated in progress

**Comment by kbabu007** [comment]
Code move training done by student.

**Comment by kbabu007** [comment]
closed
