### ISSUE TITLE
Release Version

### ISSUE THREAD

**Issue by kbabu007** [SIGC-DevOps-205/Repo-DevOps-205#12]

**Comment by karthikalucky** [comment]
In progress

**Comment by brindha2025** [comment]
Status updated to in progress

**Comment by Aarthi169** [comment]
Status updated in progress

**Comment by Santh2004** [comment]
Status updated to in progress

**Comment by Maha2405** [comment]
Status updates to in progress

**Comment by karthikalucky** [comment]
Status updated in progress

**Comment by 7Keerthana** [comment]
Status updated to in progress

**Comment by nivedha62004** [comment]
Status change into review

**Comment by mathanki2005** [comment]
Status updated in progress

**Comment by gopika030** [comment]
Status updated in progress

**Comment by DharaniShree10** [comment]
Status updated in progress

**Comment by dharanisathya** [comment]
Status updates in progress

**Comment by Durga3025** [comment]
Status updated to in progress

**Comment by Guna288** [comment]
Status updated to in progress

**Comment by bhuvanasri3101** [comment]
Status   updated  to in progress

**Comment by Ang2405** [comment]
Status updated to in progress

**Comment by Afrin2000** [comment]
Status updated to in progress

**Comment by rajeshwari031** [comment]
Status updated to in progress

**Comment by kiruthika021** [comment]
Status updated to in progress

**Comment by Kaviyas1013** [comment]
Status updated in progress

**Comment by keerthanagop** [comment]
Status updated to in progress

**Comment by Kayal0706** [comment]
Status updated in progress

**Comment by Manisha8667** [comment]
Status updated in progress

**Comment by Ranjanaj445** [comment]
Status updated to inprogress

**Comment by Rkrive** [comment]
Status updated inprogeess

**Comment by Pavithirajeganathan** [comment]
Status updated in progress

**Comment by kbabu007** [comment]
Build Release done
