### ISSUE TITLE
Configure Repo in GitHub

### ISSUE THREAD

**Issue by kbabu007** [SIGC-DevOps-205/Repo-DevOps-205#2]

**Comment by Maha2405** [comment]
Repo created   repo-maha2405

**Comment by brindha2025** [comment]
Created repo in Git up .status updated to in progress

**Comment by Aarthi169** [comment]
Repo created repo-aarthi169

**Comment by 7Keerthana** [comment]
Repo created, status updated to in progress

**Comment by nivedha62004** [comment]
Repo created repo-nivedha62004

**Comment by Guna288** [comment]
Repo created repo - gunapriya04

**Comment by revathikumarkalai** [comment]
Repo created repo - revathikumarkalai

**Comment by mathanki2005** [comment]
Repo created mathanki2005

**Comment by karthikalucky** [comment]
Repo created. Test-_repo

**Comment by dharanisathya** [comment]
Repo created Test_repo

**Comment by DharaniShree10** [comment]
Repo created 83104114101101

**Comment by arthi0245** [comment]
Repo created arthi0245

**Comment by Kayal0706** [comment]
Repo created kayal0706

**Comment by kanishka84688** [comment]
Repo created repo- kanishka84688

**Comment by Ang2405** [comment]
Repo created Ang2405

**Comment by bhuvanasri3101** [comment]
Record. Created bhuvanasri 3101

**Comment by abinayajk2005** [comment]
Repo created Repo-abinayajk2005

**Comment by Abirami2910** [comment]
Repo created Abirami2910

**Comment by Lachumi** [comment]
Repo created Repo-lachumi

**Comment by Lachumi** [comment]
Repo created repo-lachumi

**Comment by Kaveri286** [comment]
Repo created Repo-kaverisanmugam236

**Comment by salika123** [comment]
Repo created  Repo-sahayasalika

**Comment by kiruthika021** [comment]
Repo created Repo-kiruthika021

**Comment by suhashini37** [comment]
Repo created Repo-suhashini37

**Comment by nivetham2005** [comment]
Repo created repo-nivetham2005

**Comment by keerthanagop** [comment]
Repo created Repo - keerthanagop

**Comment by 7Keerthana** [comment]
Status updated to review

**Comment by Santh2004** [comment]
Status updated to in review

**Comment by Durga3025** [comment]
Status updated to in review

**Comment by Maha2405** [comment]
Status updated to review

**Comment by brindha2025** [comment]
Status updated in review

**Comment by revathikumarkalai** [comment]
Status updated in review

**Comment by Raji026** [comment]
Status updated in review

**Comment by nivedha62004** [comment]
Status change into review

**Comment by Kaviyas1013** [comment]
Repo created repo -kaviyas1013

**Comment by Shalin23574** [comment]
Status updated to in review

**Comment by Guna288** [comment]
Status change into review

**Comment by Lavs2004** [comment]
Status updated to in review

**Comment by rajeshwari031** [comment]
Repo created Repo-Rajeshwari031

**Comment by kbabu007** [comment]
Repo Configuration done by students.

**Comment by gopika030** [comment]
Status updated in review
