### ISSUE TITLE
Create New Branch

### ISSUE THREAD

**Issue by kbabu007** [SIGC-DevOps-205/Repo-DevOps-205#3]

**Comment by Manisha8667** [comment]
Status updated in progress

**Comment by Mohanapriyaganapathi** [comment]
Status updated in to progress

**Comment by Afrin2000** [comment]
Status updated in to progress

**Comment by Afrin2000** [comment]
Account can be created

**Comment by Maha2405** [comment]
Branch created  branch-maha2405

**Comment by brindha2025** [comment]
New branch created and status updated to in  progress .

**Comment by Aarthi169** [comment]
Branch created branch-aarthi169

**Comment by Manisha8667** [comment]
New branch (Manisha8667) created and status is updated in progress

**Comment by nivedha62004** [comment]
Branch created branch-nivedha62004

**Comment by Afrin2000** [comment]
Branch created branch-Afrin2000 and status is updated in progress

**Comment by Guna288** [comment]
Branch created branch - gunapriya04

**Comment by mathanki2005** [comment]
Branch created and status updated to in progress

**Comment by revathikumarkalai** [comment]
Branch create branch - revathikumarkalai

**Comment by Pavithirajeganathan** [comment]
Branch created-pavithirajeganathan and status  updated to in progress

**Comment by dharanisathya** [comment]
Branch created repo22

**Comment by Mohanapriyaganapathi** [comment]
Branch is created (Mohanapriyaganapathi )and status is updated in progress

**Comment by karthikalucky** [comment]
Branch created  test_repo

**Comment by DharaniShree10** [comment]
Branch created and status updated to in progress

**Comment by Ranjanaj445** [comment]
Branch created-ranjanaj445 and status in updated in progress

**Comment by kanishka84688** [comment]
Branch created branch-kanishka84688

**Comment by Ang2405** [comment]
Branch created and status updated to in  progress

**Comment by arthi0245** [comment]
Branch created and status updates to in progress

**Comment by bhuvanasri3101** [comment]
Branch  created and starus  updates to in progress

**Comment by Kayal0706** [comment]
Branch created and status updates to in progress

**Comment by abinayajk2005** [comment]
Branch created branch-abinayajk2005

**Comment by Abirami2910** [comment]
Branch created and status updated to in progress

**Comment by bhuvanasri3101** [comment]
Branch  created and status updates to in progress

**Comment by Lachumi** [comment]
Branch created branch-lachumi

**Comment by Kaveri286** [comment]
Branch created Branch-kaverisanmugam236

**Comment by salika123** [comment]
Branch created Branch-sahayasalika

**Comment by kiruthika021** [comment]
Branch created Branch-kiruthika

**Comment by suhashini37** [comment]
Branch created branch-suhashini37

**Comment by nivetham2005** [comment]
Branch created branch-nivetham2005

**Comment by Aarthi169** [comment]
Review

**Comment by Manisha8667** [comment]
Status is upadated in review

**Comment by keerthanagop** [comment]
Branch created branch - Keerthana V

**Comment by Maha2405** [comment]
Status updated to review

**Comment by Aarthi169** [comment]
Review

**Comment by nivedha62004** [comment]
Review

**Comment by Santh2004** [comment]
Status updated to in review

**Comment by Durga3025** [comment]
Status updated to in review

**Comment by brindha2025** [comment]
Status updated to in review

**Comment by nivedha62004** [comment]
Status change into review

**Comment by Guna288** [comment]
Status change into review

**Comment by Raji026** [comment]
Status updated to in review

**Comment by revathikumarkalai** [comment]
Status updated into review

**Comment by Kaviyas1013** [comment]
Branch created Branch-Rajeshwari

**Comment by rajeshwari031** [comment]
Branch created Branch-Rajeshwari

**Comment by kbabu007** [comment]
Branch created by all students.

**Comment by Kaviyas1013** [comment]
Branch created Branch-kaviya

**Comment by gopika030** [comment]
Status updated in review
