### ISSUE TITLE
Fetch / Clone from Main Branch

### ISSUE THREAD

**Issue by kbabu007** [SIGC-DevOps-205/Repo-DevOps-205#4]

**Comment by mathanki2005** [comment]
Working on progress

**Comment by Lavs2004** [comment]
Status updated to in progress

**Comment by kiruthika021** [comment]
Status updated  to in progress

**Comment by Aarthi169** [comment]
In review

**Comment by Maha2405** [comment]
Status updated to review

**Comment by 7Keerthana** [comment]
Status updated to review

**Comment by Santh2004** [comment]
Status updated to in review

**Comment by Durga3025** [comment]
Status updated to in review

**Comment by kiruthika021** [comment]
Status to review

**Comment by keerthanagop** [comment]
Status updated to review

**Comment by kiruthika021** [comment]
Status updated to review

**Comment by Shalin23574** [comment]
Status updated to in review

**Comment by nivedha62004** [comment]
Status change into review

**Comment by Guna288** [comment]
Status change into review

**Comment by Lavs2004** [comment]
Status updated to in review

**Comment by Raji026** [comment]
Status updated to in review

**Comment by Kaviyas1013** [comment]
Status updated into review

**Comment by revathikumarkalai** [comment]
Status updated into review

**Comment by rajeshwari031** [comment]
Status updated into review

**Comment by kbabu007** [comment]
Cloned code from Main branch.

**Comment by gopika030** [comment]
Status updated in review
