### ISSUE TITLE
Commit Code Changes

### ISSUE THREAD

**Issue by kbabu007** [SIGC-DevOps-205/Repo-DevOps-205#6]

**Comment by Pavithirajeganathan** [comment]
Status updated into progress

**Comment by Jamunaranimanoharan** [comment]
Status updated in to progress

**Comment by Ranjanaj445** [comment]
Status updated into progress

**Comment by Rkrive** [comment]
Status updated in to progress

**Comment by Rkrive** [comment]
Account has been created @Rkrive

**Comment by Ranjanaj445** [comment]
Account has been created  Ranjanaj445

**Comment by Jamunaranimanoharan** [comment]
Account has been created Jamunaranimanoharan

**Comment by Rkrive** [comment]
Account has been created @Rkrive

**Comment by Jamunaranimanoharan** [comment]
Branch is created (Jamunaranimanoharan ) and status is updated in progress

**Comment by Santh2004** [comment]
In progress

**Comment by Kaveri286** [comment]
Status updated to in progress

**Comment by Durga3025** [comment]
In progress

**Comment by bhuvanasri3101** [comment]
Status  updated  to in progress

**Comment by Pavithirajeganathan** [comment]
Status updated in progress

**Comment by kbabu007** [comment]
Code changes done by students.
